### ISSUE TITLE
add support for stlink

### ISSUE THREAD

**Issue by PicoCPP** [raspberrypi/openocd#13]
I am trying to use an stlink to program my rp2040

openocd -f interface/stlink.cfg -f target/rp2040.cfg  

And end up with this issue:
/usr/local/bin/../share/openocd/scripts/target/swj-dp.tcl:30: Error: Unknown param: -dp-id, try one of: -irlen, -irmask, -ircapture, -enable, -disable, -expected-id, or -ignore-version
in procedure 'script'

**Comment by HeadBoffin** [comment]
I fully appreciate you can use a Pico to do this, but many of us have lots of random ST-Link's - I've an original and a draw full of the cheap clones off eBay. As my IoT devices have long test times, it would be useful to use these ST-Links for monitoring but I can just double up on Pico's if they can be bought in pairs as an alternative.

**Comment by ghollingworth** [comment]
I'm guessing the STLink doesn't support multidrop SWD...

That would need to be fixed upstream first

**Comment by EthercatT** [comment]
I belive it does on the latest firmware, there's a couple of dual core STM32 parts.

**Comment by GMMan** [comment]
I believe ST-Link V3 supports multi-drop, but not necessarily earlier versions. In any case someone has to reverse engineer ST-Link's protocol for it since it's a high level adapter, not one where you could twiddle the lines yourself.

**Comment by maxgerhardt** [comment]
I'm wondering what happened after https://community.st.com/s/question/0D53W00000YVOfM/does-stlink-support-ad-v2multidrop-swd .. No confirmation from ST yet.

**Comment by mcuee** [comment]
I remember that ST-Link only supports STM32/STM8 MCUs from ST by license.

**Comment by P33M** [comment]
If you want stlink swd support, then ask ST to merge their OpenOCD patches upstream - https://github.com/STMicroelectronics/OpenOCD
We won't be doing it here.

**Comment by UweBonnes** [comment]
https://github.com/STMicroelectronics/OpenOCD does not implement multidrop for STlinks.
