### ISSUE TITLE
Linux compile error

### ISSUE THREAD

**Issue by iandownie07** [raspberrypi/openocd#23]
After following page 19 of the "getting started..." guide, I'm trying to use openocd on my installation for the pico and get the following error:

pen On-Chip Debugger 0.10.0+dev-gf8e14ec-dirty (2021-03-17-19:30)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Error: The specified debug interface was not found (bcm2835gpio)
The following debug adapters are available:
1: ftdi
2: usb_blaster
3: ft232r
4: presto
5: usbprog
6: openjtag
7: jlink
8: vsllink
9: rlink
10: ulink
11: arm-jtag-ew
12: hla
13: osbdm
14: opendous
15: sysfsgpio
16: aice
17: xds110
18: st-link

Any ideas?

Here's the openocd configuration summary:

OpenOCD configuration summary
--------------------------------------------------
MPSSE mode of FTDI based devices        yes
ST-Link Programmer                      yes (auto)
TI ICDI JTAG Programmer                 yes (auto)
Keil ULINK JTAG Programmer              yes (auto)
Altera USB-Blaster II Compatible        yes (auto)
Bitbang mode of FT232R based devices    yes (auto)
Versaloon-Link JTAG Programmer          yes (auto)
TI XDS110 Debug Probe                   yes (auto)
OSBDM (JTAG only) Programmer            yes (auto)
eStick/opendous JTAG Programmer         yes (auto)
Andes JTAG Programmer                   yes (auto)
USBProg JTAG Programmer                 yes (auto)
Raisonance RLink JTAG Programmer        yes (auto)
Olimex ARM-JTAG-EW Programmer           yes (auto)
CMSIS-DAP Compliant Debugger            no
Nu-Link Programmer                      no
Cypress KitProg Programmer              no
Altera USB-Blaster Compatible           yes (auto)
ASIX Presto Adapter                     yes (auto)
OpenJTAG Adapter                        yes (auto)
Linux GPIO bitbang through libgpiod     no
SEGGER J-Link Programmer                yes (auto)

**Comment by alex4o** [comment]
This is not a bug, you just forgot to add `--enable-bcm2835gpio`, you should always check what flags can be enabled by doing `./configure --help`.

**Comment by mcuee** [comment]
> This is not a bug, you just forgot to add `--enable-bcm2835gpio` to your `./configure` command, you should always check what flags can be enabled by doing `./configure --help`.

So this can be closed now.

**Comment by CoastalAmusementsFrank** [comment]
What do you mean by add "-enable-bcm2835gpio to your ./configure"? What configure command are you talking about?
