### ISSUE TITLE
sysfsgpio and bcm2835gpio not enabled after configurations step

### ISSUE THREAD

**Issue by tpbadger** [raspberrypi/openocd#24]
After running config command:

`./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio`

The configuration summary is missing sysfsgpio and bcm2835gpio. 

![image](https://user-images.githubusercontent.com/29150149/113387480-4ce56400-9384-11eb-82a9-5fe1ad05d940.png)

When running openocd it errors with 

`Error: The specified debug interface was not found (bcm2835gpio)`

Not sure if I have missed something or this is an issue others are having?

**Comment by tpbadger** [comment]
Ignore this! Correct me if I am wrong but is the bcm2835gpio interface for the raspberry pi to debug using SWD?

**Comment by lurch** [comment]
Yes, https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf says "If you are building on a Raspberry Pi you can also pass --enable-sysfsgpio --enable-bcm2835gpio to allow bitbanging SWD via the GPIO pins."

**Comment by sanjayadhikari007** [comment]
I am also facing same issue. Any workaround ?

**Comment by lurch** [comment]
@sanjayadhikari007 Please open a new issue, providing as much information as possible. (e.g. what instructions you're following, what commands you've run, which OS you're using, what errors you get, etc.)

**Comment by tcs-ulli** [comment]
Iam running in the same thing now, is there any new issue ? What was wrong with this issue ? I see the same information i also would add.

**Comment by tcs-ulli** [comment]
What information is missing ?
we both rebuild openocd with 

./bootstrap
./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio

then no bcm2835gpio appears in the overview 

and after 

make;;sudo make install

openocd tells that it dont knows an programmer device named bcm2835gpio...

Please tell what information you miss. Please define "enough information"
For me it was enougth information to reproduce the issue, i have no clue what you wish more

**Comment by lurch** [comment]
@tcs-ulli Apologies if my previously reply seemed curt, but a lot of users comment "I'm having the same problem" but then never follow up with extra information when requested :roll_eyes: 

Thank you for the information you've provided so far. Can you please also tell us:
Which branch of openocd did you clone? What OS are you using? What hardware are you running on?

Also, which instructions are you following? Those in https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf or some third-party website?
