### ISSUE TITLE
Upstream to the official openocd repo

### ISSUE THREAD

**Issue by perexg** [raspberrypi/openocd#28]
It would be really nice to see this fork upstreamed to the official openocd repository, so Linux distributions can pick it easily.

**Comment by aallan** [comment]
> It would be really nice to see this fork upstreamed to the official openocd repository, so Linux distributions can pick it easily.

We would love to have this upstreamed. But it's with the upstream maintainers at this point, they need to accept the PRs.

**Comment by perexg** [comment]
Perhaps, you may update the upstream status here? (Links to PR/Patches?) Thank you.

**Comment by cz172638** [comment]
try #openocd @ freenode

**Comment by cz172638** [comment]
and mailing list

**Comment by lurch** [comment]
I just did a bit of searching around and found http://openocd.zylin.com/#/q/rp2040

**Comment by perexg** [comment]
The picoprobe support is missing in the above PRs... I think that we're missing a plan for the merges. But I'm glad to see that there's work-in-progress for this.
