### ISSUE TITLE
Build fails on MacOS 

### ISSUE THREAD

**Issue by struandw** [raspberrypi/openocd#46]
This is MacOS 11.5.2, M1 chip. Build output is attached.

`./bootstrap` and `./configure --enable-picoprobe --disable-werror` both run without error.

Expected behaviour: `make -j4` finishes cleanly, per the documentation.
Observed behaviour: `make -j4` errors (output in [openocd failed build log.txt](https://github.com/raspberrypi/openocd/files/7655949/openocd.failed.build.log.txt))

**Comment by Kristine1975** [comment]
I had that error, too. It means the installed version of `texinfo` is too old. This solved the problem for me:

1. Install a newer `texinfo`, e.g. using Homebrew: `brew install texinfo`.
2. Export the path to the updated `texinfo` like so: `export PATH="/usr/local/opt/texinfo/bin:$PATH"`.
3. Run the build by calling `make`.

**Comment by aallan** [comment]
Just made a quick note of this, it'll be in the next docs update. Thanks.

**Comment by odaki** [comment]
For your reference.
When I installed texinfo in brew, it did not put symlink, so it was not used.
I solved this problem by using "brew link texinfo --force" to put symlink.
By the way, the installation binary path for Homebrew for M1 Mac is /opt/homebrew/bin.
Thank you.

**Comment by dancesWithMachines** [comment]
> Just made a quick note of this, it'll be in the next docs update. Thanks.

I encountered the same issue, related to the wrong path beeing exported, and I spend too much time investigating what was going to be a trivial thing. Please include both paths in the docs, I shouldn't have waste time, looking through github issues for solution.

**Comment by dancesWithMachines** [comment]
> I don't have a M1 Mac myself, but I guess we ought to expand the footnote here
I think this would be sufficient.

> to mention that a different path needs to be added to `PATH` on Apple Silicon Macs?
From my point of view, I think the both paths should be included. The question of how this will be done is of secondary importance.
