### ISSUE TITLE
flash Pico use openocd failed with 

### ISSUE THREAD

**Issue by ntko** [raspberrypi/openocd#52]
Followed by getting-started-with-pico.pdf
**5.3. Loading a Program**
Use picoprobe wiring connections to flash a pico through another one.
I'm running Ubuntu20.04.1 64bit, and use the following command:
`$ openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -s tcl -c "program hello_serial.elf verify reset exit"`
but failed with the following msg:
`Error: Failed to invoke ROM function FC (@00002361)`

By downloading:
openocd [rp2040.c](https://github.com/openocd-org/openocd/blob/master/src/flash/nor/rp2040.c) from openocd-org's repo, and replace 
pico/openocd/src/flash/nor/rp2040.c
then, rebuild rearberry's openocd.

`$ openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -s tcl -c "program hello_serial.elf verify reset exit"`

can flash pico successfully.

**Comment by P33M** [comment]
The upstream file is now the downstream file, so closing.
