### ISSUE TITLE
Add hint on how to disable jimtcl

### ISSUE THREAD

**Issue by ObligedTester** [raspberrypi/openocd#55]
Hello,

This might be a corner-case, but on quite few boxes I don't have git installed.
And when running ./configure for openOCD it fails "jimtcl" with just a hint to run "git submodule and git submodule update".

However it would be nice with a hint on how to disable it in the error code as can be seen for i.e "libjaylink":

`configure: error: Internal libjaylink not found, run either 'git submodule init' and 'git submodule update' or disable internal libjaylink with --disable-internal-libjaylink.`

It is possible to disable jimtcl with --disable-internal-jimtcl

Greetings,

**Comment by P33M** [comment]
>This might be a corner-case, but on quite few boxes I don't have git installed.

That's definitely a use-case that won't be supported...
