### ISSUE TITLE
Send changes upstream

### ISSUE THREAD

**Issue by rkta** [raspberrypi/openocd#56]
Any chance this is going upstream? I don't really want to maintain a
separate install just for the RPi pico.

**Comment by JamesH65** [comment]
AIUI, sending upstream is not a problem (we may already have done so), getting upstream to acknowledge and merge them has proven more difficult.

**Comment by aallan** [comment]
See for instance #39.

**Comment by stevemarple** [comment]
+1 for sending the changes upstream.

Is there any possibility of sending the picoprobe interface code upstream? It would be great to have the option of using a Pico as generic SWD and JTAG programmer in the official OpenOCD release.

**Comment by vulpes2** [comment]
picoprobe has been updated recently to include a CMSIS compatible implementation: raspberrypi/picoprobe#31, so perhaps a separate openocd fork is no longer necessary.

**Comment by P33M** [comment]
Work is actively ongoing to reduce the delta between our downstream patches and upstream. openocd 0.12-rc2 is useable, albeit without SMP support. There will be a brief interlude in adding new features as the release candidate cycle needs to complete, but 0.13 should end up at feature parity with downstream.
