### ISSUE TITLE
GDB error when debugging PIO projects on VSCode

### ISSUE THREAD

**Issue by tswan22** [raspberrypi/openocd#63]
OS: Ubuntu 22.04

Debug Setup: [picoprobe](https://github.com/raspberrypi/picoprobe), [openocd](https://github.com/raspberrypi/openocd), gdb-multiarch, arm-none-eabi, VSCode (Cortex-Debug, Cmake Tools, also see my [settings.json](https://github.com/raspberrypi/openocd/files/8985139/settings.json.txt) and [launch.json](https://github.com/raspberrypi/openocd/files/8985138/launch.json.txt))

Description: I am able to program and debug pico programs using my setup without issues except when the program contains code related to PIO. Take the [hello_pio example project](https://github.com/raspberrypi/pico-examples/tree/master/pio/hello_pio), if I start debugging (F5) the pico is programmed and debugging starts, but if I am in the "Run and Debug" view (Ctrl + Shift + D) the VARIABLES>Locals section attempts to load and then cancels, followed by the debug ending. Here are the [DEBUG_CONSOLE](https://github.com/raspberrypi/openocd/files/8985134/DEBUG_CONSOLE.txt) and [TERMINAL](https://github.com/raspberrypi/openocd/files/8985133/TERMINAL.txt) outputs.
Something interesting I noted is that if VSCode is not in the "Run and Debug" view, I am able to step through the program without problems, but if I attempt to look at "Run and Debug" view before finishing line 28 of [hello_pio: hello.c](https://github.com/raspberrypi/pico-examples/blob/master/pio/hello_pio/hello.c), the error occurs. If I look at "Run and Debug" after line 28, I am able to debug as expected.
Any ideas on how to resolve this?

Edit: After testing a few more things it seems like the issue may be related to debugging variables that have been optimized out or do not exist yet, it may not be PIO at all.

Note: I was not certain if this should be posted here, on [picoprobe GitHub](https://github.com/raspberrypi/picoprobe), or somewhere else, so please let me know

**Comment by P33M** [comment]
> Note: I was not certain if this should be posted here, on [picoprobe GitHub](https://github.com/raspberrypi/picoprobe), or somewhere else, so please let me know

Questions like these should be posted on the Raspberry Pi forum.
